Data Wrangling

In [15]:
import pandas as pd
import numpy as np
import matplotlib as plt
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"

headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]
df = pd.read_csv(url, names = headers)

In [16]:
df.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565

Identify and handle missing values

In [17]:
df.replace("?", np.nan, inplace = True)
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

Evaluate Missing Data

In [18]:
#df.isnull()  ## will return 'True' if value IS NaN/missing
#df.notnull()   ##will return 'True' if value is NOT missing

In [19]:
missing_data = df.isnull()
missing_data.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
for column in missing_data.columns.values:
#    print(column)
    print(missing_data[column].value_counts())
#    print("")

symboling
False    205
Name: count, dtype: int64
normalized-losses
False    164
True      41
Name: count, dtype: int64
make
False    205
Name: count, dtype: int64
fuel-type
False    205
Name: count, dtype: int64
aspiration
False    205
Name: count, dtype: int64
num-of-doors
False    203
True       2
Name: count, dtype: int64
body-style
False    205
Name: count, dtype: int64
drive-wheels
False    205
Name: count, dtype: int64
engine-location
False    205
Name: count, dtype: int64
wheel-base
False    205
Name: count, dtype: int64
length
False    205
Name: count, dtype: int64
width
False    205
Name: count, dtype: int64
height
False    205
Name: count, dtype: int64
curb-weight
False    205
Name: count, dtype: int64
engine-type
False    205
Name: count, dtype: int64
num-of-cylinders
False    205
Name: count, dtype: int64
engine-size
False    205
Name: count, dtype: int64
fuel-system
False    205
Name: count, dtype: int64
bore
False    201
True       4
Name: count, dtype: int64
stroke
False    201
True       4
Name: count, dtype: int64
compression-ratio
False    205
Name: count, dtype: int64
horsepower
False    203
True       2
Name: count, dtype: int64
peak-rpm
False    203
True       2
Name: count, dtype: int64
city-mpg
False    205
Name: count, dtype: int64
highway-mpg
False    205
Name: count, dtype: int64
price
False    201
True       4
Name: count, dtype: int64

Deal with Missing Data

In [23]:
#calc mean value for 'normalized-losses' column
avg_norm_loss = df["normalized-losses"].astype("float").mean(axis=0) 
print("Average of normalized-losses:", avg_norm_loss)

#replace NaN with mean value in 'normalized-losses column
df['normalized-losses'].replace(np.nan, avg_norm_loss, inplace=True)

#calc mean value for "bore" column
avg_bore = df['bore'].astype('float').mean(axis=0)
print('Average of bore:', avg_bore)

#replace NaN with mean value in "bore" column
df['bore'].replace(np.nan, avg_bore, inplace = True)

Average of normalized-losses: 122.0
Average of bore: 3.3297512437810943

/tmp/ipykernel_2641/1155837034.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['normalized-losses'].replace(np.nan, avg_norm_loss, inplace=True)

replace values

In [24]:
#calc mean value for 'stroke' column
avg_stroke = df['stroke'].astype('float').mean(axis = 0)
print('Average of stroke:', avg_stroke)

#replace NaN by mean value in 'stroke' column
df['stroke'].replace(np.nan, avg_stroke, inplace = True)

Average of stroke: 3.255422885572139

In [25]:
#calc mean value for 'horsepower'
avg_horsepower = df['hoursepower'].astype('float').mean(axis=0)
print('Average horsepower:', avg_horsepower)

KeyError: 'hoursepower'